name: githubcopilotworkshop
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - awscli
  - ipykernel
  - boto3
  - pip
  - pip:
      - notebook